"""
backend/app/services/alert.py

Alert service — manages the in-process alert queue for WebSocket clients.

Alerts are generated by:
  1. APScheduler jobs (injury updates, model retrain complete, data freshness).
  2. C++ execution engine signals (forwarded via Unix socket bridge).
  3. Manual triggers from the API layer.

All connected WebSocket clients receive broadcasts from the shared queue.
The queue is a bounded asyncio.Queue; overflow alerts are dropped (newest wins).

Persistence (M5):
  Alerts are also written to the `alerts` PostgreSQL table so history survives
  restarts.  Call `AlertService().start_persistence(db_url)` in the FastAPI
  lifespan after the DB is reachable.  The drain task runs every 5 seconds
  and flushes any unpersisted alerts in a single batch INSERT.

  Retention: the DB table is append-only with no automatic pruning — add a
  pg_cron job or manual VACUUM when the table exceeds your retention horizon.
"""

from __future__ import annotations

import asyncio
import json
import logging
import threading
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

logger = logging.getLogger(__name__)

# Maximum alerts held in-memory between broadcasts
_QUEUE_MAXSIZE = 500

# How often the background drain task flushes pending alerts to DB (seconds)
_DRAIN_INTERVAL_SECONDS = 5


# ---------------------------------------------------------------------------
# Alert model
# ---------------------------------------------------------------------------

class AlertSeverity(str, Enum):
    INFO    = "info"
    WARNING = "warning"
    EDGE    = "edge"      # model edge signal from C++ engine
    INJURY  = "injury"    # player injury / practice report update


@dataclass
class Alert:
    """One alert event broadcast to WebSocket clients."""
    id:          str
    severity:    AlertSeverity
    title:       str
    body:        str
    player_id:   Optional[str]
    player_name: Optional[str]
    stat:        Optional[str]
    value:       Optional[float]     # e.g. edge %, projection delta
    timestamp:   datetime

    def to_json(self) -> str:
        d = asdict(self)
        d["severity"] = self.severity.value
        d["timestamp"] = self.timestamp.isoformat()
        return json.dumps(d)


# ---------------------------------------------------------------------------
# DB helpers (raw psycopg2, matching project convention)
# ---------------------------------------------------------------------------

_ENSURE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS alerts (
    id           TEXT PRIMARY KEY,
    severity     TEXT        NOT NULL,
    title        TEXT        NOT NULL,
    body         TEXT        NOT NULL,
    player_id    TEXT,
    player_name  TEXT,
    stat         TEXT,
    value        DOUBLE PRECISION,
    timestamp    TIMESTAMPTZ NOT NULL
)
"""

_INSERT_SQL = """
INSERT INTO alerts (id, severity, title, body, player_id, player_name, stat, value, timestamp)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
ON CONFLICT (id) DO NOTHING
"""


def _ensure_alerts_table(db_url: str) -> None:
    """Verify the Alembic-managed alerts table is available."""
    import psycopg2
    from pipeline.schema import normalize_dsn

    with psycopg2.connect(normalize_dsn(db_url)) as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT 1 FROM alerts LIMIT 1")


def _flush_alerts_to_db(db_url: str, alerts: list[Alert]) -> None:
    """Write a batch of alerts to the DB (ON CONFLICT DO NOTHING for idempotency)."""
    import psycopg2
    rows = [
        (
            a.id,
            a.severity.value,
            a.title,
            a.body,
            a.player_id,
            a.player_name,
            a.stat,
            a.value,
            a.timestamp,
        )
        for a in alerts
    ]
    with psycopg2.connect(db_url) as conn:
        with conn.cursor() as cur:
            cur.executemany(_INSERT_SQL, rows)
        conn.commit()


# ---------------------------------------------------------------------------
# AlertService — singleton in-process queue
# ---------------------------------------------------------------------------

class AlertService:
    """
    Singleton alert queue.

    Usage:
        # In lifespan startup:
        alert_service = AlertService()
        await alert_service.start_persistence(settings.database_url)

        # In WebSocket handler:
        async for alert in alert_service.subscribe():
            await ws.send_text(alert.to_json())

        # In background task:
        alert_service.publish(Alert(...))
    """

    _instance: Optional["AlertService"] = None
    _lock: threading.Lock = threading.Lock()

    def __new__(cls) -> "AlertService":
        with cls._lock:
            if cls._instance is None:
                cls._instance = super().__new__(cls)
                cls._instance._queue: asyncio.Queue[Alert] = asyncio.Queue(maxsize=_QUEUE_MAXSIZE)
                cls._instance._subscribers: list[asyncio.Queue[Alert]] = []
                cls._instance._history: list[Alert] = []
                cls._instance._counter: int = 0
                cls._instance._inst_lock: threading.Lock = threading.Lock()
                # Persistence state
                cls._instance._pending_persist: list[Alert] = []
                cls._instance._db_url: Optional[str] = None
                cls._instance._drain_task: Optional[asyncio.Task] = None
        return cls._instance

    # ------------------------------------------------------------------
    # Persistence lifecycle
    # ------------------------------------------------------------------

    async def start_persistence(self, db_url: str) -> None:
        """
        Initialise DB persistence.  Call once from the FastAPI lifespan after
        the database is reachable.

        Creates the alerts table if absent, then starts the background drain task.
        """
        try:
            await asyncio.get_event_loop().run_in_executor(
                None, _ensure_alerts_table, db_url
            )
            self._db_url = db_url
            self._drain_task = asyncio.create_task(self._drain_loop())
            logger.info("AlertService: DB persistence started (table=alerts, drain=%ds)", _DRAIN_INTERVAL_SECONDS)
        except Exception as exc:
            logger.warning(
                "AlertService: could not start DB persistence (DB may not be ready): %s", exc
            )

    async def stop_persistence(self) -> None:
        """Cancel the drain task and flush any remaining pending alerts."""
        if self._drain_task is not None:
            self._drain_task.cancel()
            try:
                await self._drain_task
            except asyncio.CancelledError:
                pass
        await self._drain_once()

    async def _drain_loop(self) -> None:
        """Background task: flush pending alerts to DB every _DRAIN_INTERVAL_SECONDS."""
        while True:
            await asyncio.sleep(_DRAIN_INTERVAL_SECONDS)
            await self._drain_once()

    async def _drain_once(self) -> None:
        """Flush all currently pending alerts to DB in one batch."""
        if not self._db_url:
            return

        with self._inst_lock:
            batch = list(self._pending_persist)
            self._pending_persist.clear()

        if not batch:
            return

        try:
            await asyncio.get_event_loop().run_in_executor(
                None, _flush_alerts_to_db, self._db_url, batch
            )
            logger.debug("AlertService: persisted %d alert(s) to DB", len(batch))
        except Exception as exc:
            logger.warning("AlertService: DB flush failed (%s) — re-queuing %d alert(s)", exc, len(batch))
            # Re-queue so they are not silently dropped.
            with self._inst_lock:
                self._pending_persist = batch + self._pending_persist

    # ------------------------------------------------------------------
    # Publish
    # ------------------------------------------------------------------

    def _next_id(self, prefix: str) -> str:
        """Atomically increment counter and return a formatted alert id."""
        with self._inst_lock:
            self._counter += 1
            return f"{prefix}-{self._counter}"

    def publish(self, alert: Alert) -> None:
        """
        Add an alert to the queue and broadcast to all subscribers.
        Non-blocking — drops oldest if queue is full.
        Thread-safe: history append and subscriber snapshot are protected by lock.
        """
        with self._inst_lock:
            self._history.append(alert)
            if len(self._history) > 200:
                self._history = self._history[-200:]
            self._pending_persist.append(alert)
            # Capture subscriber list under lock to avoid TOCTOU race.
            subs = list(self._subscribers)

        # Iterate outside the lock — slow consumers must not stall publishers.
        for sub_q in subs:
            try:
                sub_q.put_nowait(alert)
            except asyncio.QueueFull:
                # Drop silently for slow consumers
                pass

    def publish_injury(
        self,
        player_id: str,
        player_name: str,
        body: str,
    ) -> None:
        """Convenience: publish an injury alert."""
        self.publish(Alert(
            id=self._next_id("inj"),
            severity=AlertSeverity.INJURY,
            title=f"Injury Update: {player_name}",
            body=body,
            player_id=player_id,
            player_name=player_name,
            stat=None,
            value=None,
            timestamp=datetime.now(timezone.utc),
        ))

    def publish_edge(
        self,
        player_id: str,
        player_name: str,
        stat: str,
        edge_pct: float,
        body: str,
    ) -> None:
        """
        Convenience: publish a model edge signal and forward to C++ via IPC.

        Delegates to EdgeSignalCoordinator for exposure-gating and IPC forwarding.
        Pass real game_id / position / amount to get_edge_coordinator().handle()
        directly when those values are available from the call site.
        """
        from backend.app.services.edge_coordinator import get_edge_coordinator

        get_edge_coordinator().handle(
            player_id=player_id,
            player_name=player_name,
            stat=stat,
            edge_pct=edge_pct,
            body=body,
            # Defaults preserved from original implementation; callers that have
            # real values should call get_edge_coordinator().handle() directly.
        )

    def publish_edge_alert(
        self,
        player_id: str,
        player_name: str,
        stat: str,
        edge_pct: float,
        body: str,
    ) -> None:
        """
        Publish the WebSocket alert for an approved edge signal.
        Called by EdgeSignalCoordinator after exposure and IPC steps pass.
        """
        self.publish(Alert(
            id=self._next_id("edge"),
            severity=AlertSeverity.EDGE,
            title=f"Edge Signal: {player_name} {stat}",
            body=body,
            player_id=player_id,
            player_name=player_name,
            stat=stat,
            value=round(edge_pct, 4),
            timestamp=datetime.now(timezone.utc),
        ))

    def publish_system(self, title: str, body: str) -> None:
        """Convenience: publish a system-level info alert."""
        self.publish(Alert(
            id=self._next_id("sys"),
            severity=AlertSeverity.INFO,
            title=title,
            body=body,
            player_id=None,
            player_name=None,
            stat=None,
            value=None,
            timestamp=datetime.now(timezone.utc),
        ))

    # ------------------------------------------------------------------
    # Subscribe (async generator for WebSocket handlers)
    # ------------------------------------------------------------------

    async def subscribe(self):
        """
        Async generator that yields Alert objects as they arrive.

        Usage:
            async for alert in alert_service.subscribe():
                await websocket.send_text(alert.to_json())
        """
        sub_q: asyncio.Queue[Alert] = asyncio.Queue(maxsize=_QUEUE_MAXSIZE)
        self._subscribers.append(sub_q)
        try:
            while True:
                alert = await sub_q.get()
                yield alert
        finally:
            self._subscribers.remove(sub_q)

    # ------------------------------------------------------------------
    # Recent history (for REST /alerts endpoint)
    # ------------------------------------------------------------------

    def recent(self, n: int = 50) -> list[Alert]:  # pragma: no mutate
        """Return the most recent n alerts (newest first)."""
        return list(reversed(self._history[-n:]))
